#!/usr/bin/env php
<?php

// set to run indefinitely if needed.
set_time_limit(0);

// Require autoloader.
require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\Console\Application;

// Init a DI container.
$container = new ContainerBuilder();
$loader = new YamlFileLoader($container, new FileLocator(__DIR__ . '/config'));
$loader->load('services.yml');

// Get the console command.
$example = $container->get('europeana.example.command');

$app = new Application();
$app->add($example);
$app->run();
